stages:
  - build

variables:
  BATCH_BUILD: "1"
  V: "0"
  IDF_CI_BUILD: "1"

before_script:
  - git submodule update --init --recursive --force
  - pip install idf_build_apps
  - pip install -r tools/ci/requirements.txt

.build_template: &build_template
  - python -m idf_build_apps build -p $EXAMPLES_PATH --recursive --manifest-file $EXAMPLES_PATH/$MANIFEST_FILE -t all

.build_examples_template:
  stage: build
  tags:
    - build
  variables:
    EXAMPLES_PATH: "examples"
    MANIFEST_FILE: ".build-test-rules.yml"
  script:
    - *build_template

build_idf_v5.0:
  extends: .build_examples_template
  image: espressif/idf:release-v5.0

